# Generated by Django 2.2.17 on 2020-11-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets', models.TextField()),
                ('manual', models.TextField()),
                ('auto', models.TextField()),
                ('dtype', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets', models.TextField()),
                ('manual', models.TextField()),
                ('auto', models.TextField()),
                ('dtype', models.TextField()),
            ],
        ),
    ]
